from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtWidgets import QMainWindow
import sys

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(315, 299)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(parent=self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 321, 261))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayoutWidget = QtWidgets.QWidget(parent=self.tab)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(0, 90, 311, 134))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setVerticalSpacing(6)
        self.gridLayout.setObjectName("gridLayout")
        self.pushButton_5 = QtWidgets.QPushButton(parent=self.gridLayoutWidget)
        self.pushButton_5.setMinimumSize(QtCore.QSize(40, 40))
        self.pushButton_5.setObjectName("pushButton_5")
        self.gridLayout.addWidget(self.pushButton_5, 2, 0, 1, 1)
        self.pushButton_17 = QtWidgets.QPushButton(parent=self.gridLayoutWidget)
        self.pushButton_17.setMinimumSize(QtCore.QSize(40, 40))
        self.pushButton_17.setObjectName("pushButton_17")
        self.gridLayout.addWidget(self.pushButton_17, 1, 2, 1, 1)
        self.pushButton_8 = QtWidgets.QPushButton(parent=self.gridLayoutWidget)
        self.pushButton_8.setMinimumSize(QtCore.QSize(40, 40))
        self.pushButton_8.setObjectName("pushButton_8")
        self.gridLayout.addWidget(self.pushButton_8, 0, 1, 1, 1)
        self.pushButton_7 = QtWidgets.QPushButton(parent=self.gridLayoutWidget)
        self.pushButton_7.setMinimumSize(QtCore.QSize(40, 40))
        self.pushButton_7.setObjectName("pushButton_7")
        self.gridLayout.addWidget(self.pushButton_7, 1, 0, 1, 1)
        self.pushButton_4 = QtWidgets.QPushButton(parent=self.gridLayoutWidget)
        self.pushButton_4.setMinimumSize(QtCore.QSize(40, 40))
        self.pushButton_4.setObjectName("pushButton_4")
        self.gridLayout.addWidget(self.pushButton_4, 2, 2, 1, 1)
        self.pushButton_6 = QtWidgets.QPushButton(parent=self.gridLayoutWidget)
        self.pushButton_6.setMinimumSize(QtCore.QSize(40, 40))
        self.pushButton_6.setObjectName("pushButton_6")
        self.gridLayout.addWidget(self.pushButton_6, 2, 1, 1, 1)
        self.pushButton_16 = QtWidgets.QPushButton(parent=self.gridLayoutWidget)
        self.pushButton_16.setMinimumSize(QtCore.QSize(40, 40))
        self.pushButton_16.setObjectName("pushButton_16")
        self.gridLayout.addWidget(self.pushButton_16, 1, 1, 1, 1)
        self.pushButton_9 = QtWidgets.QPushButton(parent=self.gridLayoutWidget)
        self.pushButton_9.setMinimumSize(QtCore.QSize(40, 40))
        self.pushButton_9.setObjectName("pushButton_9")
        self.gridLayout.addWidget(self.pushButton_9, 0, 2, 1, 1)
        self.pushButton_18 = QtWidgets.QPushButton(parent=self.gridLayoutWidget)
        self.pushButton_18.setMinimumSize(QtCore.QSize(40, 40))
        self.pushButton_18.setObjectName("pushButton_18")
        self.gridLayout.addWidget(self.pushButton_18, 0, 0, 1, 1)
        self.lineEdit = QtWidgets.QLineEdit(parent=self.tab)
        self.lineEdit.setGeometry(QtCore.QRect(0, 0, 311, 81))
        self.lineEdit.setObjectName("lineEdit")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.verticalLayoutWidget = QtWidgets.QWidget(parent=self.tab_2)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 80, 101, 151))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.pushButton = QtWidgets.QPushButton(parent=self.verticalLayoutWidget)
        self.pushButton.setMinimumSize(QtCore.QSize(40, 40))
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout_4.addWidget(self.pushButton)
        self.pushButton_3 = QtWidgets.QPushButton(parent=self.verticalLayoutWidget)
        self.pushButton_3.setMinimumSize(QtCore.QSize(40, 40))
        self.pushButton_3.setObjectName("pushButton_3")
        self.verticalLayout_4.addWidget(self.pushButton_3)
        self.pushButton_2 = QtWidgets.QPushButton(parent=self.verticalLayoutWidget)
        self.pushButton_2.setMinimumSize(QtCore.QSize(40, 40))
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalLayout_4.addWidget(self.pushButton_2)
        self.lineEdit_2 = QtWidgets.QLineEdit(parent=self.tab_2)
        self.lineEdit_2.setGeometry(QtCore.QRect(0, 0, 321, 71))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.horizontalLayoutWidget = QtWidgets.QWidget(parent=self.tab_2)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(100, 80, 211, 51))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_33 = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget)
        self.pushButton_33.setMinimumSize(QtCore.QSize(40, 40))
        self.pushButton_33.setObjectName("pushButton_33")
        self.horizontalLayout.addWidget(self.pushButton_33)
        self.pushButton_19 = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget)
        self.pushButton_19.setMinimumSize(QtCore.QSize(40, 40))
        self.pushButton_19.setObjectName("pushButton_19")
        self.horizontalLayout.addWidget(self.pushButton_19)
        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(parent=self.tab_2)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(100, 130, 211, 51))
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.pushButton_34 = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget_3)
        self.pushButton_34.setMinimumSize(QtCore.QSize(40, 40))
        self.pushButton_34.setObjectName("pushButton_34")
        self.horizontalLayout_3.addWidget(self.pushButton_34)
        self.pushButton_35 = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget_3)
        self.pushButton_35.setMinimumSize(QtCore.QSize(40, 40))
        self.pushButton_35.setObjectName("pushButton_35")
        self.horizontalLayout_3.addWidget(self.pushButton_35)
        self.horizontalLayoutWidget_4 = QtWidgets.QWidget(parent=self.tab_2)
        self.horizontalLayoutWidget_4.setGeometry(QtCore.QRect(100, 180, 211, 51))
        self.horizontalLayoutWidget_4.setObjectName("horizontalLayoutWidget_4")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_4)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.pushButton_36 = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget_4)
        self.pushButton_36.setMinimumSize(QtCore.QSize(40, 40))
        self.pushButton_36.setObjectName("pushButton_36")
        self.horizontalLayout_4.addWidget(self.pushButton_36)
        self.pushButton_37 = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget_4)
        self.pushButton_37.setMinimumSize(QtCore.QSize(40, 40))
        self.pushButton_37.setObjectName("pushButton_37")
        self.horizontalLayout_4.addWidget(self.pushButton_37)
        self.tabWidget.addTab(self.tab_2, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 315, 22))
        self.menubar.setObjectName("menubar")
        self.menuOption = QtWidgets.QMenu(parent=self.menubar)
        self.menuOption.setObjectName("menuOption")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.action = QtGui.QAction(parent=MainWindow)
        self.action.setObjectName("action")
        self.action_2 = QtGui.QAction(parent=MainWindow)
        self.action_2.setObjectName("action_2")
        self.action_3 = QtGui.QAction(parent=MainWindow)
        self.action_3.setObjectName("action_3")
        self.action_4 = QtGui.QAction(parent=MainWindow)
        self.action_4.setObjectName("action_4")
        self.action_5 = QtGui.QAction(parent=MainWindow)
        self.action_5.setObjectName("action_5")
        self.menuOption.addAction(self.action)
        self.menuOption.addAction(self.action_2)
        self.menuOption.addAction(self.action_3)
        self.menuOption.addAction(self.action_4)
        self.menuOption.addAction(self.action_5)
        self.menubar.addAction(self.menuOption.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Kalkulator"))
        self.pushButton_5.setText(_translate("MainWindow", "5"))
        self.pushButton_17.setText(_translate("MainWindow", "7"))
        self.pushButton_8.setText(_translate("MainWindow", "3"))
        self.pushButton_7.setText(_translate("MainWindow", "4"))
        self.pushButton_4.setText(_translate("MainWindow", "0"))
        self.pushButton_6.setText(_translate("MainWindow", "9"))
        self.pushButton_16.setText(_translate("MainWindow", "6"))
        self.pushButton_9.setText(_translate("MainWindow", "8"))
        self.pushButton_18.setText(_translate("MainWindow", "1"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Tab 1"))
        self.pushButton.setText(_translate("MainWindow", "1"))
        self.pushButton_3.setText(_translate("MainWindow", "5"))
        self.pushButton_2.setText(_translate("MainWindow", "8"))
        self.pushButton_33.setText(_translate("MainWindow", "3"))
        self.pushButton_19.setText(_translate("MainWindow", "4"))
        self.pushButton_34.setText(_translate("MainWindow", "6"))
        self.pushButton_35.setText(_translate("MainWindow", "7"))
        self.pushButton_36.setText(_translate("MainWindow", "9"))
        self.pushButton_37.setText(_translate("MainWindow", "0"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Tab 2"))
        self.menuOption.setTitle(_translate("MainWindow", "Option"))
        self.action.setText(_translate("MainWindow", "*"))
        self.action_2.setText(_translate("MainWindow", "/"))
        self.action_3.setText(_translate("MainWindow", "+"))
        self.action_4.setText(_translate("MainWindow", "-"))
        self.action_5.setText(_translate("MainWindow", "="))


class MainWindow(QMainWindow):
    def __init__(self):
        super().__init__()
        self.ui = Ui_MainWindow()
        self.ui.setupUi(self)
        # Variabel untuk menyimpan operator dan angka
        self.first_num = None
        self.operator = None
        # Menghubungkan tombol dengan fungsi
        self.connect_signals()

    def connect_signals(self):
        # Tombol angka di Tab 1
        self.ui.pushButton.clicked.connect(lambda: self.append_digit("1", self.ui.lineEdit))
        self.ui.pushButton_2.clicked.connect(lambda: self.append_digit("8", self.ui.lineEdit))
        self.ui.pushButton_3.clicked.connect(lambda: self.append_digit("5", self.ui.lineEdit))
        self.ui.pushButton_5.clicked.connect(lambda: self.append_digit("5", self.ui.lineEdit))
        self.ui.pushButton_6.clicked.connect(lambda: self.append_digit("9", self.ui.lineEdit))
        self.ui.pushButton_7.clicked.connect(lambda: self.append_digit("4", self.ui.lineEdit))
        self.ui.pushButton_8.clicked.connect(lambda: self.append_digit("3", self.ui.lineEdit))
        self.ui.pushButton_9.clicked.connect(lambda: self.append_digit("8", self.ui.lineEdit))
        self.ui.pushButton_18.clicked.connect(lambda: self.append_digit("1", self.ui.lineEdit))
        self.ui.pushButton_17.clicked.connect(lambda: self.append_digit("7", self.ui.lineEdit))
        self.ui.pushButton_4.clicked.connect(lambda: self.append_digit("0", self.ui.lineEdit))
        self.ui.pushButton_16.clicked.connect(lambda: self.append_digit("6", self.ui.lineEdit))

        # Tombol angka di Tab 2
        self.ui.pushButton.clicked.connect(lambda: self.append_digit("1", self.ui.lineEdit_2))
        self.ui.pushButton_2.clicked.connect(lambda: self.append_digit("8", self.ui.lineEdit_2))
        self.ui.pushButton_3.clicked.connect(lambda: self.append_digit("5", self.ui.lineEdit_2))
        self.ui.pushButton_33.clicked.connect(lambda: self.append_digit("3", self.ui.lineEdit_2))
        self.ui.pushButton_19.clicked.connect(lambda: self.append_digit("4", self.ui.lineEdit_2))
        self.ui.pushButton_34.clicked.connect(lambda: self.append_digit("6", self.ui.lineEdit_2))
        self.ui.pushButton_35.clicked.connect(lambda: self.append_digit("7", self.ui.lineEdit_2))
        self.ui.pushButton_36.clicked.connect(lambda: self.append_digit("9", self.ui.lineEdit_2))
        self.ui.pushButton_37.clicked.connect(lambda: self.append_digit("0", self.ui.lineEdit_2))

        # Tombol operasi
        self.ui.action.triggered.connect(lambda: self.set_operator("*", self.ui.lineEdit))
        self.ui.action_2.triggered.connect(lambda: self.set_operator("/", self.ui.lineEdit))
        self.ui.action_3.triggered.connect(lambda: self.set_operator("+", self.ui.lineEdit))
        self.ui.action_4.triggered.connect(lambda: self.set_operator("-", self.ui.lineEdit))
        self.ui.action_5.triggered.connect(lambda: self.calculate_result(self.ui.lineEdit))

        # Tombol operasi di Tab 2
        self.ui.action.triggered.connect(lambda: self.set_operator("*", self.ui.lineEdit_2))
        self.ui.action_2.triggered.connect(lambda: self.set_operator("/", self.ui.lineEdit_2))
        self.ui.action_3.triggered.connect(lambda: self.set_operator("+", self.ui.lineEdit_2))
        self.ui.action_4.triggered.connect(lambda: self.set_operator("-", self.ui.lineEdit_2))
        self.ui.action_5.triggered.connect(lambda: self.calculate_result(self.ui.lineEdit_2))

    def append_digit(self, digit, line_edit):
        current_text = line_edit.text()
        line_edit.setText(current_text + digit)

    def set_operator(self, operator, line_edit):
        self.first_num = line_edit.text() 
        self.operator = operator
        line_edit.setText(self.first_num + " " + operator + " ")

    def calculate_result(self, line_edit):
        expression = line_edit.text()  
        try:
            result = eval(expression)
        except Exception:
            result = ""
        line_edit.setText(str(result))


if __name__ == "__main__":
    app = QtWidgets.QApplication(sys.argv)
    mainWindow = MainWindow()
    mainWindow.show()
    sys.exit(app.exec())
